language: node_js
sudo: false
node_js:
 - "stable"
install:
 - npm uninstall mdbootstrap
 - npm install
 - npm install mdbootstrap@4.7.7
script:
 - npm run build
cache:
 directories:
 - "node_modules"
